def add_music(fs):
    fs.put(open('Balenciaga - Nippandab.mp3', 'rb'), content_type="audio/mpeg",
                        filename="Balenciaga - Nippandab.mp3")
    fs.put(open('Everything They S4Y - Smash Into Pieces.mp3', 'rb'), content_type="audio/mpeg",
                        filename="Everything They S4Y - Smash Into Pieces.mp3")
    fs.put(open('Hell and Back - Radio Tapok.mp3', 'rb'), content_type="audio/mpeg",
                        filename="Hell and Back - Radio Tapok.mp3")
    fs.put(open('Hypnodancer - Little Big.mp3', 'rb'), content_type="audio/mpeg",
                        filename="Hypnodancer - Little Big.mp3")
    fs.put(open('Links 2 3 4 - Rammstein.mp3', 'rb'), content_type="audio/mpeg",
                        filename="Links 2 3 4 - Rammstein.mp3")
    fs.put(open('Monster - Skillet.mp3', 'rb'), content_type="audio/mpeg",
                        filename="Monster - Skillet.mp3")
    fs.put(open('Oblivion - Amber van Day.mp3', 'rb'), content_type="audio/mpeg",
                        filename="Oblivion - Amber van Day.mp3")
    fs.put(open('Precious - Raizer.mp3', 'rb'), content_type="audio/mpeg",
                        filename="Precious - Raizer.mp3")
    fs.put(open('Secret - Zera.mp3', 'rb'), content_type="audio/mpeg",
                        filename="Secret - Zera.mp3")
    fs.put(open('Sweater Weather - Julian Perretta.mp3', 'rb'), content_type="audio/mpeg",
                        filename="Sweater Weather - Julian Perretta.mp3")